### ISSUE TITLE
Fields in CSV device data incorrect

### ISSUE THREAD

**Issue by michaellass** [ttnmapper/ttnmapper-web#13]
The number of fields and their contents in the CSV device data do not match the headings in the same document. You can find an example here:
https://ttnmapper.org/devices/csv-pg.php?device=eui-70b3d57ed004579a&startdate=&enddate=&gateways=on&lines=on&points=on

The headings show 20 fields of which `experiment name` is the last one. The actual data lines only have 19 fields (there are 18 commas) of which `experiment name` is the second to last one. In above's example, everything up to including `accuracy meters` seems correct. I cannot see where exactly the error comes into play as none of `hdop`, `sats`, `location provider` and `user_agent` are set in my data.

The data is coming from the [TTN Mapper Phone Surveyor](https://github.com/ttnmapper/ttnmapper-android-v3) app as it is currently available in the Google Play Store. But due to the wrong number of commas, I rather think the problem is at the website. The TTN application is a v3 application which might play a role as well.

I also noticed the following, but I think this is expected due to the [current status of the v3 migration](https://github.com/ttnmapper/documentation/blob/master/project_status.md):
* Data points on the map do not show connections to any gateways although correctly shown in the Android app (see https://ttnmapper.org/devices/?device=eui-70b3d57ed004579a&startdate=&enddate=&gateways=on&lines=on&points=on)
* Data points from experiments are not mapable at all

**Comment by jpmeijers** [comment]
Thanks for reporting. The missing columns was indeed a bug caused by how php handles sql results. That has been fixed now.

The other two points you mention are indeed due to the migration. The example you provided doesn't work because the way gateways are identified changed slightly, and that page can't find the gateway location. It's something that need to be fixed at some point.

Experiment maps also still need to be added.
