### ISSUE TITLE
Request to include network cluster in gateway data shown

### ISSUE THREAD

**Issue by tomtobback** [ttnmapper/ttnmapper-web#15]
Hi, from my discussion on the [TTN forum](https://www.thethingsnetwork.org/forum/t/application-and-gateway-region-selection/14654/5) i understand that the TTN regional clusters are not integrated yet, so it is important that people in the same region use the same cluster, for devices and gateways. For some regions this might not be so obvious, e.g. Asia, so it would be helpful if the cluster information can be shown in the gateway data on TTNmapper. Thanks

**Comment by jpmeijers** [comment]
Marking this as #wontfix as TTI needs to decide if the same tenant on different clusters is the same network or not. TTN Mapper identifies gateways and devices on a per-network bases using a "network ID". We can't go and change this network ID arbitrarily at any point, as data is already stored in the database based on this.

At the start I wanted to handle tenants on clusters as different networks, but Johan convinced me otherwise in a packet broker issue discussion:
https://github.com/packetbroker/api/issues/23#issuecomment-822548645

If we need to change it at this point all mapping data up until now for TTS-CE (V3) will be lost.
